version: "3.9"

services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: celery-worker
    command: celery -A worker.celery_app worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
